### ISSUE TITLE
critical error with usher 0.6.1+

### ISSUE THREAD

**Issue by patcoll** [hassox/pancake#2]
```
NoMethodError: undefined method `app=' for #<App::Router:0x1c92a4c>
```

Where "App" is the name of my app. It appeared an API change in Usher was causing this, so I  applied this patch.

```
diff --git a/lib/pancake/stack/configuration.rb b/lib/pancake/stack/configuration.rb
index 1d2c0dd..4dc6de0 100644
--- a/lib/pancake/stack/configuration.rb
+++ b/lib/pancake/stack/configuration.rb
@@ -35,7 +35,7 @@ class Pancake::Stack::Configuration
       unless stack.nil?
         r = stack.router.dup
         r.configuration = self
-        r.app = app
+        r.default(app)
         r.configuration = self
         r
       end
```

Which ended up giving me this error when I loaded up the `/` route:

   undefined method `call' for {:action=>"get__"}:Hash

being thrown from `determine_respondant` on line 128 of `usher-0.6.3/lib/usher/interface/rack.rb`

downgrading to usher 0.6.0 fixes the problem. (for pancake 0.1.28)

**Comment by hassox** [comment]
This is fixed
