### ISSUE TITLE
bundler 0.9.x

### ISSUE THREAD

**Issue by orlin** [hassox/pancake#4]
Pancake (micro) is not loading with the latest Bundler.  I use code that otherwise works with Sinatra.  Here is the error http://astrolin.heroku.com/.  If I try to explicitly require pancake the old way (after bundler's begin / resque / end) I get an extlib issue.  Well, here's the code http://gist.github.com/313197

**Comment by hassox** [comment]
I've not used bundler with pancake before so not sure on this one.  I'll give it a crack though and see what's up.

**Comment by orlin** [comment]
This appears to be fixed with the new short_stack gem.  A single shared Gemfile when mounting stacks?  Or require the Gemfile of each mounted stack from the root master...  Closing the issue anyway.
